apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-300"
  name: argocd-extra-after-cilium
  namespace: argocd
 
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default 
  syncPolicy:
   automated:
     prune: false
     selfHeal: false
   syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan

  source:
    path: 'argocd-extra-after-cilium'
    repoURL: '{{ .Values.spec.source.repoURL }}'
