apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-160"
  name: elastic-operator
  namespace: argocd
 
spec:
  destination:
    namespace: elastic-operator
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  syncPolicy:
   automated:
     prune: false
     selfHeal: false
   syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan

  source:
    path: ''
    repoURL: 'https://helm.elastic.co'
    targetRevision: 2.10.0
    chart: eck-operator
    helm:
      values: |-
        webhook:
          enabled: false
        config:
          containerRegistry: repo.simra.cloud/elasticsearch
