apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
  name: elastic-exporter
  namespace: argocd
 
spec:
  destination:
    namespace: elastic
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  syncPolicy:
   automated:
     prune: false
     selfHeal: false
   syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan

  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 5.4.0
    chart: prometheus-elasticsearch-exporter
    helm:
      values: |-
        es:
          uri: http://elastic:Y39O8q211fJSl7f4XdX2ps6T@logcluster-es-http.elastic:9200
          sslSkipVerify: true     
