apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: keycloak
  namespace: argocd
 
spec:
  destination:
    namespace: keycloak
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=orphan
  source:
    repoURL: https://codecentric.github.io/helm-charts
    targetRevision: 18.4.4
    chart: keycloak
