apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-590"
  name: kubernetes-replicator
  namespace: argocd
 
spec:
  destination:
    namespace: kubernetes-replicator
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  syncPolicy:
   automated:
     prune: false
     selfHeal: false
   syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan

  source:
    path: ''
    repoURL: 'https://helm.mittwald.de'
    targetRevision: v2.9.1
    chart: kubernetes-replicator
