apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-600"
  name: openebs
  namespace: argocd
 
spec:
  destination:
    namespace: openebs
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  syncPolicy:
   automated:
     prune: false
     selfHeal: false
   syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan
  source:
    repoURL: 'https://openebs.github.io/lvm-localpv'
    targetRevision: 1.4.0
    chart: lvm-localpv
