apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-590"
  name: openebs-extra
  namespace: argocd
 
spec:
  destination:
    namespace: openebs
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  syncPolicy:
   automated:
     prune: false
     selfHeal: false
   syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan

  source:
    path: 'openebs-extra'
    targetRevision: HEAD
    repoURL: '{{ .Values.spec.source.repoURL }}'
