apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-500"
  name: pgo
  namespace: argocd
 
spec:
  destination:
    namespace: pgo
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=orphan
  source:
    path: 'pgo'
    repoURL: '{{ .Values.spec.source.repoURL }}'
