apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-600"
  name: sealedsecret
  namespace: argocd
 
spec:
  destination:
    namespace: sealedsecret
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  syncPolicy:
   automated:
     prune: false
     selfHeal: false
   syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan

  source:
    path: ''
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: 2.13.4
    chart: sealed-secrets
    helm:
      values: ''
      parameters:
        - name: keyrenewperiod
          value: 43800h
